name: Slack Alarm for PR review

on:
  pull_request_review:
    types: [submitted]  # Pull Request에 대한 리뷰가 제출되었을때
  pull_request_review_comment:
    types: [created, edited]  # Pull Request의 리뷰 코멘트가 생성되거나 편집되었을때

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:

      ### Slack Alarm for PR review ###
      - name: Notify Slack on PR review
        id: slack-success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": ${{ secrets.SLACK_CHANNEL }},
              "attachments": [
                {
                  "color": "#0e5fd5",
                  "title": ":speech_balloon: Review Pull-Request",
                  "title_link": "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}",
                  "text": "PR 리뷰 제출 or 코멘트 생성 및 편집",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "PR_Branch",
                      "value": "${{ github.head_ref }}",
                      "short": true
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK